version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: testRubicon
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      #By removing this line the data from the database is not persisted
      #- /tmp/mydb:/var/lib/mysql
      #Scripts here only executed when the database starts for the first time
      - ./scrips/init:/docker-entrypoint-initdb.d
      - ./scrips/conf:/etc/mysql/conf.d
      - ./scrips/csvData:/etc/mysql/tmp
      #- /home/imarti/Documents/rubicon/dataModel/DockerDataModel/scrips/init:/docker-entrypoint-initdb.d
      #- /home/imarti/Documents/rubicon/dataModel/DockerDataModel/scrips/conf:/etc/mysql/conf.d
      #- /home/imarti/Documents/rubicon/dataModel/DockerDataModel/scrips/csvData:/etc/mysql/tmp
