version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      #try out with it
      #MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      #By removing this line the data from the database is not persisted
      #- /tmp/mydb:/var/lib/mysql
      #Scripts here only executed when the database starts for the first time
      - /home/imarti/Documents/rubicon/dataModel/DockerDataModel/scrips:/docker-entrypoint-initdb.d
